### ISSUE TITLE
Could not load type `ArrayPoolMemoryAllocator` when project depends on `ImageSharp` version 2.1.3 

### ISSUE THREAD

**Issue by Crauzer** [SixLabors/ImageSharp.Textures#13]
![image](https://user-images.githubusercontent.com/18646077/212501507-31f672aa-01b3-4a7c-8c78-30c659aad13e.png)

The exception seems to be caused by: https://github.com/SixLabors/ImageSharp.Textures/blob/381923859d0bf427657f7424450ab4ec133f0da2/src/ImageSharp.Textures/Configuration.cs#L91

`ArrayPoolMemoryAllocator` doesn't seem to exist anymore in the latest version of `ImageSharp` which is likely causing the issue.

**Comment by brianpopow** [comment]
I have updated the ImageSharp reference to 2.1.3, try the ImageSharp.Textures version alpha.0.139

**Comment by Crauzer** [comment]
Thanks for the quick fix!
